### ISSUE TITLE
Add support for TIMING descriptor, 1722.1-2021 clause 7.2.34

### ISSUE THREAD

**Issue by andrew-elder** [L-Acoustics/avdecc#116]

**Comment by christophe-calmejane** [comment]
Thanks Andrew.
I was just (yesterday) about to enter this ticket, looking at the correct way to link `CLOCK_SOURCE` descriptor to a `TIMING` / `PTP_INSTANCE` one and figured out the `clock_source_type` field should be set to `EXTERNAL` (to be confirmed by 1722.1, because it's not clear in the latest specification as it specifically says _via a Jack_).

Do you want to contribute this or willing to wait a bit (was planing on doing it in the coming weeks)?

**Comment by andrew-elder** [comment]
Hi Chris, It sounds like we should wait and see what 1722.1 says/confirms? I'm not it too much of a hurry - just need to be able to select the clock source via 1722.1 (and maybe Hive).

**Comment by christophe-calmejane** [comment]
Yes, probably best to be sure of the _correct_ way to do things. I already got an unofficial confirmation of the way to do it, but the question will be asked on the 1722.1 reflector pretty soon.
Although it doesn't prevent the implementation of the descriptors, just how an entity should define its fields correctly.
